### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by Kline-x** [linvon/coreader#2]
请问reader里的processChunk方法里的linesPool.Put(chunk)作用是什么呢?

**Comment by linvon** [comment]
> 请问reader里的processChunk方法里的linesPool.Put(chunk)作用是什么呢?

chunk 里的数据已经用完了，不再需要了。就把 chunk 占用的这块内存再放回 linesPool，减少内存再分配和 GC 的次数

**Comment by Kline-x** [comment]
> > 请问reader里的processChunk方法里的linesPool.Put(chunk)作用是什么呢?
> 
> chunk 里的数据已经用完了，不再需要了。就把 chunk 占用的这块内存再放回 linesPool，减少内存再分配和 GC 的次数

还能这样的吗？那chunk里存的数据不也是一起丢回去了？

**Comment by linvon** [comment]
> > > 请问reader里的processChunk方法里的linesPool.Put(chunk)作用是什么呢?
> > 
> > 
> > chunk 里的数据已经用完了，不再需要了。就把 chunk 占用的这块内存再放回 linesPool，减少内存再分配和 GC 的次数
> 
> 还能这样的吗？那chunk里存的数据不也是一起丢回去了？

使用 sync.Pool 的初衷就是减小内存分配压力，数据自然也会写在内存里丢进去，但既然已经用完了就不关心数据了，下一个时刻或者其他 goroutine 再取出来这块内存时会向里写入新的数据

**Comment by Kline-x** [comment]
> 其他 goroutine 再取出来这块内存时会向里写入新的数据

那么linesPool和stringPool弄成全局变量可以吗？

**Comment by linvon** [comment]
> > 其他 goroutine 再取出来这块内存时会向里写入新的数据
> 
> 那么linesPool和stringPool弄成全局变量可以吗？

可以的，实际使用并没有区别

**Comment by Kline-x** [comment]
> 可以的，实际使用并没有区别

好的，谢谢解答

**Comment by Kline-x** [comment]
> > > 其他 goroutine 再取出来这块内存时会向里写入新的数据
> > 
> > 
> > 那么linesPool和stringPool弄成全局变量可以吗？
> 
> 可以的，实际使用并没有区别

能简单地说一下这样分片读，和一行一行地读的区别吗？我还是不太明白两者有什么不同之处

**Comment by linvon** [comment]
> > > > 其他 goroutine 再取出来这块内存时会向里写入新的数据
> > > 
> > > 
> > > 那么linesPool和stringPool弄成全局变量可以吗？
> > 
> > 
> > 可以的，实际使用并没有区别
> 
> 能简单地说一下这样分片读，和一行一行地读的区别吗？我还是不太明白两者有什么不同之处

可以看一下 [我博客的这篇文章](http://www.linvon.cn/posts/golang%E5%BF%AB%E9%80%9F%E8%AF%BB%E5%8F%96%E5%A4%84%E7%90%86%E5%A4%A7%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6/)

简单来讲读取文件需要从磁盘进行IO读取，而 CPU 访问磁盘和访问内存的速度是差别很大的，最快的方式是一次把整个文件都读到内存，但文件如果太大内存是扛不住的，但每次只读一行就会导致 CPU 频繁的切换去读取磁盘，浪费性能。因此开发者就可以选择做中和，一个读取一个块，至于块的大小就看自己的具体情况分配了

**Comment by Kline-x** [comment]
> ，但文件如果太大内存是扛不住的

按照这么说，那只有当块内容大于一行内容的时候，才算是有用，不然就是白费劲

**Comment by linvon** [comment]
> > ，但文件如果太大内存是扛不住的
> 
> 按照这么说，那只有当块内容大于一行内容的时候，才算是有用，不然就是白费劲

是的，毕竟是用来处理”大“文件的。如果文本太小，反而是负提升

**Comment by Kline-x** [comment]
> > > ，但文件如果太大内存是扛不住的
> > 
> > 
> > 按照这么说，那只有当块内容大于一行内容的时候，才算是有用，不然就是白费劲
> 
> 是的，毕竟是用来处理”大“文件的。如果文本太小，反而是负提升

logsSlice不是已经是一个根据换行符分割的切片了吗？如果要处理每一行的内容，直接遍历这个切片不就行了吗？为什么还要下面这段：
	chunkSize := 300
	n := len(logsSlice)
	noOfThread := n / chunkSize

	if n%chunkSize != 0 {
		noOfThread++
	}

	for i := 0; i < (noOfThread); i++ {
		wg2.Add(1)
		go func(s int, e int) {
			defer wg2.Done() //to avaoid deadlocks
			for i := s; i < e; i++ {
				text := logsSlice[i]
				if len(text) == 0 {
					continue
				}
				lineProcess(text)
			}
		}(i*chunkSize, int(math.Min(float64((i+1)*chunkSize), float64(len(logsSlice)))))
	}

	wg2.Wait()
	logsSlice = nil

**Comment by linvon** [comment]
> 为什么还要下面这段：

你可以理解为这部分是对提取后的很多行再分块，然后利用 goroutine 的并发特性进行批处理，以充分利用 CPU，当然如果你的行处理中都是 CPU 密集型操作的话，实际相对于直接行处理的提升并不大

**Comment by Kline-x** [comment]
> 你可以理解为这部分是对提取后的很多行再分块，

我直接遍历切片，每一行开个goroutine去处理，不也是一样的吗？

**Comment by linvon** [comment]
> > 你可以理解为这部分是对提取后的很多行再分块，
> 
> 我直接遍历切片，每一行开个goroutine去处理，不也是一样的吗？

开 goroutine 也是有开销的，开得太多自然是负优化

**Comment by Kline-x** [comment]
> > > 你可以理解为这部分是对提取后的很多行再分块，
> > 
> > 
> > 我直接遍历切片，每一行开个goroutine去处理，不也是一样的吗？
> 
> 开 goroutine 也是有开销的，开得太多自然是负优化

懂了，就是开一个折中数量的goroutine,每个goroutine处理几行数据

**Comment by linvon** [comment]
> > > > 你可以理解为这部分是对提取后的很多行再分块，
> > > 
> > > 
> > > 我直接遍历切片，每一行开个goroutine去处理，不也是一样的吗？
> > 
> > 
> > 开 goroutine 也是有开销的，开得太多自然是负优化
> 
> 懂了，就是开一个折中数量的goroutine,每个goroutine处理几行数据

是的

**Comment by Kline-x** [comment]
> > > > > 你可以理解为这部分是对提取后的很多行再分块，
> > > > 
> > > > 
> > > > 我直接遍历切片，每一行开个goroutine去处理，不也是一样的吗？
> > > 
> > > 
> > > 开 goroutine 也是有开销的，开得太多自然是负优化
> > 
> > 
> > 懂了，就是开一个折中数量的goroutine,每个goroutine处理几行数据
> 
> 是的

那最后这句logsSlice = nil的意思是手动释放内存吗？

**Comment by linvon** [comment]
> 那最后这句logsSlice = nil的意思是手动释放内存吗？

不写的话 GC 也会帮你收的，个人猜测可能会更快被回收一点

**Comment by Kline-x** [comment]
> > 那最后这句logsSlice = nil的意思是手动释放内存吗？
> 
> 不写的话 GC 也会帮你收的，个人猜测可能会更快被回收一点

谢谢大佬解答

**Comment by Kline-x** [comment]
请问您跑的时候会出现too many concurrent operations on a single file or socket吗？

**Comment by linvon** [comment]
> 请问您跑的时候会出现too many concurrent operations on a single file or socket吗？

没有的，可能是你的文件过于庞大，并发跑的太多了
